freelancer_subscription:
    resource: "@FreelancerBundle/Controller/SubscriptionController.php"
    type:     annotation

notif:
    resource: "@NotifBundle/Resources/config/routing.yml"
    prefix:   /notif

esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

freelancer_training:
    resource: "@FreelancerBundle/Controller/TrainingController.php"
    type:     annotation

my_app_admin:
    resource: "@MyAppAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

my_app_job_owner:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing.yml"
    prefix:   /jobowner

freelancer:
    resource: "@FreelancerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications





