my_app_admin:
    resource: "@MyAppAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

my_app_job_owner:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing.yml"
    prefix:   /jobowner

skills_list:
    resource: "@FreelancerBundle/Resources/config/routing/skills.yml"
    prefix:   /skills

Demands_list:
    resource: "@FreelancerBundle/Resources/config/routing/demande.yml"
    prefix:   /demande

Offer:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing/offer.yml"
    prefix:   /offer

project:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing/project.yml"
    prefix:   /jobowner/project

Examen:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing/examen.yml"
    prefix:   /jobowner/examen

freelancer:
    resource: "@FreelancerBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

