freelancer_homepage:
    path:     /
    defaults: { _controller: FreelancerBundle:Default:index }
freelancer_home:
    path:     /
    defaults: { _controller: "FreelancerBundle:Freelancer:home" }
    methods:  DELETE

freelancer_admin_home:
    path:     /admin
    defaults: { _controller: MyAppAdminBundle:Admin:Admin }

freelancer_Freelancer:
    path:     /Freelancer
    defaults: { _controller: FreelancerBundle:Freelancer:Freelancer }

freelancer_JobOwner:
    path:     /JobOwner
    defaults: { _controller: MyAppJobOwnerBundle:JobOwner:jobOwner }

freelancer_alluser:
    path:     /Alluser
    defaults: { _controller: FreelancerBundle:Freelancer:Alluser }

freelancer_Showfreelancer:
    path:     /Freelancer/showfreelancer/{email}
    defaults: { _controller: FreelancerBundle:Freelancer:showfreelancer }

freelancer_Showjobowner:
    path:     /Freelancer/showjobowner/{email}
    defaults: { _controller: FreelancerBundle:Freelancer:showjobowner }

freelancer_EditProfile:
    path:     /Freelancer/Editprofile
    defaults: { _controller: FreelancerBundle:Freelancer:Editprofile }
