freelancer_homepage:
    path:     /
    defaults: { _controller: FreelancerBundle:Default:index }
freelancer_home:
    path:     /
    defaults: { _controller: "FreelancerBundle:Freelancer:home" }
    methods:  DELETE

freelancer_admin_home:
    path:     /admin
    defaults: { _controller: MyAppAdminBundle:Admin:Admin }

freelancer_Freelancer:
    path:     /Freelancer
    defaults: { _controller: FreelancerBundle:Freelancer:Freelancer }

freelancer_JobOwner:
    path:     /JobOwner
    defaults: { _controller: MyAppJobOwnerBundle:JobOwner:jobOwnerr }

notification_mark_all_as_seen:
    path:     /{notifiable}/markAllAsSeen
    defaults: { _controller: "NotifBundle:Notification:markAllAsSeen" }

mysubscriptions:
    path:     /mysubscriptions
    defaults: { _controller: FreelancerBundle:Subscription:mysubscriptions }


