my_app_job_owner_offer:
    resource: "@MyAppJobOwnerBundle/Resources/config/routing/offer.yml"
    prefix:   /offer

my_app_job_owner_homepage:
    path:     /
    defaults: { _controller: MyAppJobOwnerBundle:JobOwner:jobOwner}
    methods:  GET

my_app_job_owner_payment_page:
    path:     /payment/new/{id}
    defaults: { _controller: MyAppJobOwnerBundle:Payment:Payment}

