<?php

namespace MyApp\FreelancerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LivraisonRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends EntityRepository
{
}
